services:
  msel-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379  # internal access
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6377:6379"  # host:container => access Redis on localhost:6377
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge