services:
  msel-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Add any environment variables your FastAPI app needs
      # - DATABASE_URL=postgresql://user:pass@host:port/db
      - REDIS_URL=redis://redis:6379
    volumes:
      # Mount your FastAPI app code (for development)
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis  # Ensure Redis starts before FastAPI
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6377:6377"
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge