services:
  msel-generator:
    container_name: msel_generator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://msel_redis:6379  # internal access
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: msel_redis
    ports:
      - "6377:6379"  # host:container => access Redis on localhost:6377
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # mount custom config
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - app_network

volumes:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge