services:
  msel-generator:
    container_name: msel_generator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://msel_redis:6379  # internal access
      - PG_DSN=postgresql://postgres:password@msel_postgres:5432/msel_db
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: msel_redis
    ports:
      - "6377:6379"  # host:container => access Redis on localhost:6377
    restart: unless-stopped
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: msel_postgres
    ports:
      - "5433:5432"  # host:container => access Postgres on localhost:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=msel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

# Named volumes for persistent data
volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge