services:
  msel-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Add any environment variables your FastAPI app needs
      # - DATABASE_URL=postgresql://user:pass@host:port/db
      # - REDIS_URL=redis://localhost:6379
    volumes:
      # Mount your FastAPI app code (for development)
      - .:/app
    restart: unless-stopped
    # Optional: if you need to connect to the main server's database
    # networks:
    #   - shared-network

# Optional: Create a shared network if you want direct container-to-container communication
# networks:
#   shared-network:
#     external: true